### ISSUE TITLE
multi-lines in markdown table cells

### ISSUE THREAD

**Issue by huanggze** [Mivinci/hugo-theme-minima#18]
Hi, how can we break lines in markdown table cells. I would expect something like below, but it doesn't work in minima. Thanks for the help.

|column|
|---|
|Hello,<br>world!|
|Hello, world!|

```
|column|
|---|
|Hello,<br>world!|
|Hello, world!|
```

**Comment by Mivinci** [comment]
@huanggze Hi, me again :)

Hugo's default markdown renderer (Goldmark) doesn't allow raw HTML written in markdown, but you can turn it off by adding something to your config file.

If you're using `config.toml`, it's
```toml
[markup.goldmark.renderer]
unsafe = true
```

If you're using `config.yml`, it's
```yaml
markup:
  goldmark:
    renderer:
      unsafe: true
```

Then you can use `<br>` to break lines anywhere in a post.
