### ISSUE TITLE
Don't add facebook social svg icon

### ISSUE THREAD

**Issue by memclutter** [mivinci/hugo-theme-minima#31]
**Steps to reproduce:**

1. Install and init site

    ```
    hugo new site blog
    cd blog
    git submodule add --depth 1 https://github.com/mivinci/hugo-theme-minima.git themes/minima
    ```

2. Copy & paste example [config](https://github.com/Mivinci/hugo-theme-minima/blob/main/exampleSite/config.toml) 
3. Fixed theme name `hugo-theme-minima` to `minima`
4. Run site and check it working
    
    ```
    hugo server -D
    ```

5. Add new param.social item

    ```
    [[params.social]]
    name = "facebook"
    url = "https://facebook.com/"
    svg = ""
    ```

**Excepted:** facebook icon must be visible
**Actual:** no facebook icon 

**Screenshot**

![image](https://user-images.githubusercontent.com/7972741/200046950-75476e6d-1975-40df-b856-fcc260118475.png)

config.toml
```toml
baseURL = "http://h.xjj.pub"
languageCode = "en-us"
title = "Hi Folks"
copyright = "© XJJ 2022"
googleAnalytics = ""

# paginate decides the number of the newest posts
# that'll be shown on the home page.
paginate = 6

# theme is the name of the hugo theme you're gonna use,
# `hugo-theme-minima` is put here only for debuging,
# just name it what's under your theme directory.
theme = "minima"

# Author has some of your information to be shown on the home page.
[author]
name = "XJJ"
slogon = "A tech lover from Earth 🌍"
description = "This is Minima, a clean and minimal Hugo theme porting from the [Hexo Minima](https://github.com/adisaktijrs/hexo-theme-minima). Except for everything from Hexo Minima like dark/light mode, Hugo Minima supports KaTeX, Mermaid, comments and some taxonomies like categories, series and tags. I created this using SASS, VanillaJS and the most importantly, Hugo. 😁"


[params]
# iam is the beginning words of your self-introduction.
iam = "I am"
# The subtitle will be shown after the title of your blog site.
# e.g. "title - subtitle".
subtitle = ""
# Comment decides the comment plugin to be used on your blog site, 
# e.g. disqus, utterances, ovo.
comment = "utterances"
# Timeformat, no matter what format to use, make it the second day of Jan. 2006
timeformat = "Jan 02, 2006"
# switch for turning on/off lights.
switch = ["🌚", "🌝"]
# default theme. e.g. light, dark, system
defaultTheme = "system"
# If set true, date of posts will be shown in the homepage.
displayDate = true
# If set true, users can select text from your post.
selectable = true
# Custom global font. notice: `globalFontFamily` won't be working
# on texts in some special positions like on titles
globalFontFamily = ""
# If set true, all your posts will use the chosen comment plugin
# except those with a `comment: false` in their front-matter
commentOnAllPosts = true
# toc decides the shape of the toc button. e.g. default, lines, bar
toc = "lines"

recent = "Recent Posts"
older = "Older Posts"

# Disqus configuration
[params.disqus]
shortname = "hugo-minima"

# Utterances configuration
# Full doc's at https://utteranc.es
# **notice**: if you're going to use utterances, you must change the 
# `repo` to your own repo address that stores comments on your site
[params.utterances]
repo = "mivinci/hugo-theme-minima"
issueTerm = "pathname"

# **deprecated**
# OvO is a comment plugin written by the author of Minima.
# It is enabled when params.comment is set "ovo". You can
# have a live view on https://ovo.js.org. If you are using 
# disqus or utterance, just ignore this.
[params.ovo]
server = ""
placeholder = ""


# Params.social is an array containing your social network accounts,
# Each has a lowercase name, a svg formatted icon and a url to the 
# webpage of your account. They will be shown at the bottom of every
# page of your blog. 
# Be sure the svgs you use must have both its width and its height
# set 18. If you don't wanna put the svg code in this config file, 
# since they are too long, you can instead save them to the 
# `data/svg.toml` file under the root directory of your blog. 
# in that file, each line must be formatted as `name = '<svg>'`
# where `<svg>` is the svg code.
[[params.social]]
name = "github"  
url = "https://github.com/mivinci/hugo-theme-minima"
svg = ""
[[params.social]]
name = "linkedin"
url = "https://linkedin/in/leonard-mivinci-63895317a"
svg = ""
[[params.social]]
name = "twitter"
url = "https://twitter.com/Leonard14733745"
svg = ""
[[params.social]]
name = "facebook"
url = "https://facebook.com/"
svg = ""
[[params.social]]
name = "rss"
url = "/index.xml"
svg = ""

# If set, titles and links of the topk newest posts extracted from 
# the feeds will be displayed in the home page. Note that the feeds
# providers have to make their 'Access-Control-Allow-Origin' contain
# your domain, otherwise the feeds cannot be fetched.
[params.friends]
feeds = ["https://h.xjj.pub/index.xml"]
topk = 3
title = "Friends' Posts"
proxy = "" # reserved


# Menu.main is an array that's used to decide what entries can be shown
# on the navigator of yur blog. You can use a weight to make them ordered.
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Categories"
url = "/categories"
weight = 2
[[menu.main]]
name = "Series"
url = "/series"
weight = 3
[[menu.main]]
name = "About"
url = "/about"
weight = 4


# You can classify your posts by setting taxanomies in the front matter
# e.g.
#     categories = ["dev"]
#     series = ["Building an RPC server"]
#     tags = ["hugo", "golang"]
# A little suggestion: one post belongs to one series or one category or multiple tags.
[taxonomies]
category = "categories"
tag = "tags"
series = "series"


# Fields below make sure all the codes in a post are
# highlighted correctly, so better not edit them.
[markup.highlight]
lineNos = true
noClasses = false
```
